// Code generated by entc, DO NOT EDIT.

package numbertoken

const (
	// Label holds the string label denoting the numbertoken type in the database.
	Label = "number_token"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"

	// EdgeHex holds the string denoting the hex edge name in mutations.
	EdgeHex = "hex"

	// Table holds the table name of the numbertoken in the database.
	Table = "number_tokens"
	// HexTable is the table the holds the hex relation/edge.
	HexTable = "hexes"
	// HexInverseTable is the table name for the Hex entity.
	// It exists in this package in order to avoid circular dependency with the "hex" package.
	HexInverseTable = "hexes"
	// HexColumn is the table column denoting the hex relation/edge.
	HexColumn = "number_token_hex"
)

// Columns holds all SQL columns for numbertoken fields.
var Columns = []string{
	FieldID,
	FieldValue,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ValueValidator is a validator for the "value" field. It is called by the builders before save.
	ValueValidator func(int) error
)
