// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andrewmthomas87/catan/ent/predicate"
	"github.com/andrewmthomas87/catan/ent/road"
)

// RoadUpdate is the builder for updating Road entities.
type RoadUpdate struct {
	config
	hooks    []Hook
	mutation *RoadMutation
}

// Where adds a new predicate for the RoadUpdate builder.
func (ru *RoadUpdate) Where(ps ...predicate.Road) *RoadUpdate {
	ru.mutation.predicates = append(ru.mutation.predicates, ps...)
	return ru
}

// SetX sets the "x" field.
func (ru *RoadUpdate) SetX(i int) *RoadUpdate {
	ru.mutation.ResetX()
	ru.mutation.SetX(i)
	return ru
}

// AddX adds i to the "x" field.
func (ru *RoadUpdate) AddX(i int) *RoadUpdate {
	ru.mutation.AddX(i)
	return ru
}

// SetY sets the "y" field.
func (ru *RoadUpdate) SetY(i int) *RoadUpdate {
	ru.mutation.ResetY()
	ru.mutation.SetY(i)
	return ru
}

// AddY adds i to the "y" field.
func (ru *RoadUpdate) AddY(i int) *RoadUpdate {
	ru.mutation.AddY(i)
	return ru
}

// Mutation returns the RoadMutation object of the builder.
func (ru *RoadUpdate) Mutation() *RoadMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *RoadUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ru.hooks) == 0 {
		affected, err = ru.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoadMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ru.mutation = mutation
			affected, err = ru.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ru.hooks) - 1; i >= 0; i-- {
			mut = ru.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ru.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ru *RoadUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *RoadUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *RoadUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ru *RoadUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   road.Table,
			Columns: road.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: road.FieldID,
			},
		},
	}
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.X(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldX,
		})
	}
	if value, ok := ru.mutation.AddedX(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldX,
		})
	}
	if value, ok := ru.mutation.Y(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldY,
		})
	}
	if value, ok := ru.mutation.AddedY(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldY,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{road.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoadUpdateOne is the builder for updating a single Road entity.
type RoadUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoadMutation
}

// SetX sets the "x" field.
func (ruo *RoadUpdateOne) SetX(i int) *RoadUpdateOne {
	ruo.mutation.ResetX()
	ruo.mutation.SetX(i)
	return ruo
}

// AddX adds i to the "x" field.
func (ruo *RoadUpdateOne) AddX(i int) *RoadUpdateOne {
	ruo.mutation.AddX(i)
	return ruo
}

// SetY sets the "y" field.
func (ruo *RoadUpdateOne) SetY(i int) *RoadUpdateOne {
	ruo.mutation.ResetY()
	ruo.mutation.SetY(i)
	return ruo
}

// AddY adds i to the "y" field.
func (ruo *RoadUpdateOne) AddY(i int) *RoadUpdateOne {
	ruo.mutation.AddY(i)
	return ruo
}

// Mutation returns the RoadMutation object of the builder.
func (ruo *RoadUpdateOne) Mutation() *RoadMutation {
	return ruo.mutation
}

// Save executes the query and returns the updated Road entity.
func (ruo *RoadUpdateOne) Save(ctx context.Context) (*Road, error) {
	var (
		err  error
		node *Road
	)
	if len(ruo.hooks) == 0 {
		node, err = ruo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoadMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ruo.mutation = mutation
			node, err = ruo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ruo.hooks) - 1; i >= 0; i-- {
			mut = ruo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ruo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *RoadUpdateOne) SaveX(ctx context.Context) *Road {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *RoadUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *RoadUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ruo *RoadUpdateOne) sqlSave(ctx context.Context) (_node *Road, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   road.Table,
			Columns: road.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: road.FieldID,
			},
		},
	}
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Road.ID for update")}
	}
	_spec.Node.ID.Value = id
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.X(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldX,
		})
	}
	if value, ok := ruo.mutation.AddedX(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldX,
		})
	}
	if value, ok := ruo.mutation.Y(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldY,
		})
	}
	if value, ok := ruo.mutation.AddedY(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: road.FieldY,
		})
	}
	_node = &Road{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{road.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return _node, nil
}
