// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andrewmthomas87/catan/ent/hex"
	"github.com/andrewmthomas87/catan/ent/robber"
)

// RobberCreate is the builder for creating a Robber entity.
type RobberCreate struct {
	config
	mutation *RobberMutation
	hooks    []Hook
}

// SetHexID sets the "hex" edge to the Hex entity by ID.
func (rc *RobberCreate) SetHexID(id int) *RobberCreate {
	rc.mutation.SetHexID(id)
	return rc
}

// SetNillableHexID sets the "hex" edge to the Hex entity by ID if the given value is not nil.
func (rc *RobberCreate) SetNillableHexID(id *int) *RobberCreate {
	if id != nil {
		rc = rc.SetHexID(*id)
	}
	return rc
}

// SetHex sets the "hex" edge to the Hex entity.
func (rc *RobberCreate) SetHex(h *Hex) *RobberCreate {
	return rc.SetHexID(h.ID)
}

// Mutation returns the RobberMutation object of the builder.
func (rc *RobberCreate) Mutation() *RobberMutation {
	return rc.mutation
}

// Save creates the Robber in the database.
func (rc *RobberCreate) Save(ctx context.Context) (*Robber, error) {
	var (
		err  error
		node *Robber
	)
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RobberMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			node, err = rc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RobberCreate) SaveX(ctx context.Context) *Robber {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (rc *RobberCreate) check() error {
	return nil
}

func (rc *RobberCreate) sqlSave(ctx context.Context) (*Robber, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rc *RobberCreate) createSpec() (*Robber, *sqlgraph.CreateSpec) {
	var (
		_node = &Robber{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: robber.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: robber.FieldID,
			},
		}
	)
	if nodes := rc.mutation.HexIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   robber.HexTable,
			Columns: []string{robber.HexColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: hex.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RobberCreateBulk is the builder for creating many Robber entities in bulk.
type RobberCreateBulk struct {
	config
	builders []*RobberCreate
}

// Save creates the Robber entities in the database.
func (rcb *RobberCreateBulk) Save(ctx context.Context) ([]*Robber, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Robber, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RobberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RobberCreateBulk) SaveX(ctx context.Context) []*Robber {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
